apps/phonebook/src/Entity/Phone.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PhoneRepository")
 */
class Phone
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="bigint", unique=true)
     */
    private $phone_number;

    /**
     * @ORM\Column(type="integer")
     */
    private $user_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Share", mappedBy="phone")
     */
    private $share;

    public function __construct()
    {
        $this->share = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Share[]
     */
    public function getShare(): Collection
    {
        return $this->share;
    }

    public function addShare(Share $share): self
    {
        if (!$this->share->contains($share)) {
            $this->share[] = $share;
            $share->setPhone($this);
        }

        return $this;
    }

    public function removeShare(Share $share): self
    {
        if ($this->share->contains($share)) {
            $this->share->removeElement($share);
            // set the owning side to null (unless already changed)
            if ($share->getPhone() === $this) {
                $share->setPhone(null);
            }
        }

        return $this;
    }
}

apps/phonebook/src/Form/PhoneType.php
<?php

namespace App\Form;

use App\Entity\Phone;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PhoneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('phone_number')
            ->add('name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Phone::class,
        ]);
    }
}

apps/phonebook/src/Controller/PhoneController.php
<?php

namespace App\Controller;

use App\Entity\Phone;
use App\Entity\Share;
use App\Entity\User;
use App\Form\PhoneType;
use App\Form\ShareType;
use App\Repository\PhoneRepository;
use App\Repository\ShareRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @IsGranted("IS_AUTHENTICATED_FULLY")
 * @Route("/phone")
 */
class PhoneController extends AbstractController
{
    /**
     * @Route("/", name="phone_index", methods={"GET"})
     */
    public function index(PhoneRepository $phoneRepository, ShareRepository $shareRepository, Security $security): Response
    {
        $user = $security->getUser();

        $phones = $phoneRepository->findBy(['user_id' => $user->getId()]);
        $shared = $shareRepository->findBy(['user_id' => $user->getId()]);
        $sharedPhones = [];

        foreach ($shared as $share)
        {
            $phone = $phoneRepository->findOneBy(['id' => $share->getPhoneId()]);
            array_push($sharedPhones, $phone);
        }

        return $this->render('phone/index.html.twig', [
            'phones' => $phones, 'shared' => $sharedPhones
        ]);
    }

    /**
     * @Route("/new", name="phone_new", methods={"GET","POST"})
     */
    public function new(Request $request, Security $security): Response
    {
        $user = $security->getUser();

        $phone = new Phone();
        $form = $this->createForm(PhoneType::class, $phone);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $phone->setUserId($user->getId());
            $entityManager->persist($phone);
            $entityManager->flush();

            return $this->redirectToRoute('phone_index');
        }

        return $this->render('phone/new.html.twig', [
            'phone' => $phone,
            'form' => $form->createView(),
        ]);
    }



    /**
     * @Route("/{id}", name="phone_show", methods={"GET"})
     */
    public function show(Phone $phone, Security $security): Response
    {
        $user = $security->getUser();

        if ($user->getId() == $phone->getUserId()) {
            return $this->render('phone/show.html.twig', [
                'phone' => $phone,
            ]);
        } else {
            return new Response('Cant touch this');
            //  return $this->createAccessDeniedException();
        }
    }

    /**
     * @Route("/{id}/edit", name="phone_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Phone $phone, Security $security): Response
    {
        $user = $security->getUser();

        if ($user->getId() == $phone->getUserId()) {
            $form = $this->createForm(PhoneType::class, $phone);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $this->getDoctrine()->getManager()->flush();

                return $this->redirectToRoute('phone_index');
            }

            return $this->render('phone/edit.html.twig', [
                'phone' => $phone,
                'form' => $form->createView(),
            ]);
        } else {
            return new Response('Cant touch this');
            //  return $this->createAccessDeniedException();
        }

    }

    /**
     * @Route("/{id}", name="phone_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Phone $phone, Security $security): Response
    {
        $user = $security->getUser();

        if ($user->getId() == $phone->getUserId()) {
            if ($this->isCsrfTokenValid('delete'.$phone->getId(), $request->request->get('_token'))) {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->remove($phone);
                $entityManager->flush();
            }

            return $this->redirectToRoute('phone_index');
        } else {
            return new Response('Cant touch this');
            //  return $this->createAccessDeniedException();
        }

    }


}

apps/phonebook/templates/phone/_delete_form.html.twig
<form method="post" action="{{ path('phone_delete', {'id': phone.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ phone.id) }}">
    <button class="btn">Delete</button>
</form>

apps/phonebook/templates/phone/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

apps/phonebook/templates/phone/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Phone{% endblock %}

{% block body %}
    <h1>Edit Phone</h1>

    {{ include('phone/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('phone_index') }}">back to list</a>

    {{ include('phone/_delete_form.html.twig') }}
{% endblock %}

apps/phonebook/templates/phone/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Phone index{% endblock %}

{% block body %}
    <h1>Phone Book</h1>

    <h2>Your phone numbers</h2>
    <div>
        <a href="{{ path('phone_new') }}">Create new</a>
    </div>

    {% if phones %}

    <table class="table">
        <thead>
            <tr>
                <th>Contact name</th>
                <th>Phone_number</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for phone in phones %}
            <tr>
                <td>{{ phone.name }}</td>
                <td>{{ phone.phoneNumber }}</td>
                <td>
                    <a href="{{ path('phone_show', {'id': phone.id}) }}">show</a>
                    <a href="{{ path('phone_edit', {'id': phone.id}) }}">edit</a>
                    <a href="{{ path('share', {'id': phone.id}) }}">share</a>
                </td>
            </tr>
            {% for share in phone.share %}
                <tr>
                    <td>You are sharing this contact with:</td>
                    <td>{{ share.user.name }}</td>
                    <td>{{ include('share/_delete_form.html.twig') }}</td>
                </tr>
            {% endfor %}

        {% endfor %}
        </tbody>
    </table>
{% else %}
        <small colspan="5">no records found</small>
{% endif %}

    <h2>Shared phone numbers</h2>

    {% if shared %}
    <table class="table">
        <thead>
        <tr>
            <th>Contact name</th>
            <th>Phone_number</th>
        </tr>
        </thead>
        <tbody>
        {% for share in shared %}
            <tr>
                <td>{{ share.name }}</td>
                <td>{{ share.phoneNumber }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
        <small colspan="5">no records found</small>
    {% endif %}

{% endblock %}

apps/phonebook/templates/phone/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Phone{% endblock %}

{% block body %}
    <h1>Create new Phone</h1>

    {{ include('phone/_form.html.twig') }}

    <a href="{{ path('phone_index') }}">back to list</a>
{% endblock %}

apps/phonebook/templates/phone/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Phone{% endblock %}

{% block body %}
    <h1>Phone</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ phone.id }}</td>
            </tr>
            <tr>
                <th>Phone_number</th>
                <td>{{ phone.phoneNumber }}</td>
            </tr>
            <tr>
                <th>User_id</th>
                <td>{{ phone.userId }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ phone.name }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('phone_index') }}">back to list</a>
{% if app.user.id == phone.userId %}
    <a href="{{ path('phone_edit', {'id': phone.id}) }}">edit</a>
{% endif %}

    {{ include('phone/_delete_form.html.twig') }}
{% endblock %}